name: Sync Issues to YouTrack

on:
  issues:
    types:
      - opened

jobs:
  sync_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Send Issue to YouTrack
        env:
          YOUTRACK_API_URL: ${{ secrets.YOUTRACK_API_URL }}
          YOUTRACK_API_TOKEN: ${{ secrets.YOUTRACK_API_TOKEN }}
        run: |
          echo "Preparing to sync issue to YouTrack"
          
          # Issue-Daten aus GitHub Event
          ISSUE_TITLE=$(jq -r '.issue.title' $GITHUB_EVENT_PATH)
          ISSUE_BODY=$(jq -r '.issue.body' $GITHUB_EVENT_PATH)
          ISSUE_HTML_URL=$(jq -r '.issue.html_url' $GITHUB_EVENT_PATH)
          
          # JSON-Payload für YouTrack
          JSON_PAYLOAD=$(jq -n --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" --arg url "$ISSUE_HTML_URL" --arg project "0-1" '{
            summary: $title,
            description: "\($body)\n\nGitHub Issue: \($url)",
            project: { id: $project }
          }')
          
          # Anfrage an YouTrack senden
          curl -X POST "$YOUTRACK_API_URL" \
            -H "Authorization: Bearer $YOUTRACK_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD"
